// Auto-generated by AppTuner Podfile — update when adding new expo modules.
import ExpoModulesCore
import EXAV
import ExpoBlur
import ExpoCamera
import ExpoClipboard
import EXConstants
import ExpoContacts
import ExpoCrypto
import ExpoDevice
import ExpoFileSystem
import ExpoFont
import ExpoHaptics
import ExpoImage
import ExpoLinearGradient
import ExpoLinking
import ExpoLocalAuthentication
import ExpoLocation
import ExpoMediaLibrary
import ExpoNetwork
import ExpoScreenOrientation
import ExpoSecureStore
import ExpoSensors
import ExpoSharing
import ExpoSpeech
import ExpoSQLite
import ExpoStoreReview
import ExpoWebBrowser

@objc(ExpoModulesProvider)
public class ExpoModulesProvider: ModulesProvider {
  public override func getModuleClasses() -> [AnyModule.Type] {
    return [
      VideoViewModule.self,
      BlurViewModule.self,
      CameraViewModule.self,
      ClipboardModule.self,
      ConstantsModule.self,
      ContactsModule.self,
      ContactAccessButtonModule.self,
      CryptoModule.self,
      AesCryptoModule.self,
      DeviceModule.self,
      FileSystemModule.self,
      FontLoaderModule.self,
      FontUtilsModule.self,
      HapticsModule.self,
      ImageModule.self,
      LinearGradientModule.self,
      ExpoLinkingModule.self,
      LocalAuthenticationModule.self,
      LocationModule.self,
      MediaLibraryModule.self,
      NetworkModule.self,
      ScreenOrientationModule.self,
      SecureStoreModule.self,
      AccelerometerModule.self,
      BarometerModule.self,
      DeviceMotionModule.self,
      GyroscopeModule.self,
      MagnetometerModule.self,
      MagnetometerUncalibratedModule.self,
      PedometerModule.self,
      SharingModule.self,
      SpeechModule.self,
      SQLiteModule.self,
      StoreReviewModule.self,
      WebBrowserModule.self,
    ]
  }

  public override func getAppDelegateSubscribers() -> [ExpoAppDelegateSubscriber.Type] {
    return [
      FileSystemBackgroundSessionHandler.self,
      LinkingAppDelegateSubscriber.self,
      ScreenOrientationAppDelegate.self,
    ]
  }

  public override func getReactDelegateHandlers() -> [ExpoReactDelegateHandlerTupleType] {
    return []
  }
}
